lst = list(map(int, open(0).read().split()))
lst.sort()
if lst[0] == lst[1] == lst[2] == 60: print("Equilateral")
elif sum(lst) == 180 and (lst[0] == lst[1] or lst[1] == lst[2]): print("Isosceles")
elif sum(lst) == 180: print("Scalene")
else: print("Error")